name: Laravel CI

on:
  pull_request:
    branches: [ main, master, staging ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.*'

      - name: Install dependencies
        run: composer install
